"""empty message

Revision ID: 3268532ff0a9
Revises: 6215d247e59d
Create Date: 2020-08-25 06:37:08.927905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3268532ff0a9'
down_revision = '6215d247e59d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('actorName', sa.String(length=80), nullable=True))
    op.drop_column('actors', 'actorNa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('actorNa', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('actors', 'actorName')
    # ### end Alembic commands ###
