"""empty message

Revision ID: 358e447ffca1
Revises: 74ee926cc3b2
Create Date: 2020-08-27 11:10:46.686890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358e447ffca1'
down_revision = '74ee926cc3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_actors_actor_id_fkey', 'movies_actors', type_='foreignkey')
    op.drop_constraint('movies_actors_movie_id_fkey', 'movies_actors', type_='foreignkey')
    op.drop_column('movies_actors', 'actor_id')
    op.drop_column('movies_actors', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies_actors', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies_actors', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movies_actors_movie_id_fkey', 'movies_actors', 'movies', ['movie_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('movies_actors_actor_id_fkey', 'movies_actors', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
