"""empty message

Revision ID: 3e4cd16f30c1
Revises: e09a85de397c
Create Date: 2020-08-21 01:15:48.984166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e4cd16f30c1'
down_revision = 'e09a85de397c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'movie_details_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_details_test', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
