"""empty message

Revision ID: 430602fac0f9
Revises: 86ac441ca630
Create Date: 2020-08-29 13:17:55.668434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '430602fac0f9'
down_revision = '86ac441ca630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies_actors', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies_actors', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
