"""empty message

Revision ID: 6215d247e59d
Revises: 748f37eca9d2
Create Date: 2020-08-25 06:36:14.267228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6215d247e59d'
down_revision = '748f37eca9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('actorNa', sa.String(length=80), nullable=True))
    op.drop_column('actors', 'actorName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('actorName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('actors', 'actorNa')
    # ### end Alembic commands ###
