"""empty message

Revision ID: 66027b4b8496
Revises: e578255c657a
Create Date: 2020-08-27 08:50:24.589623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66027b4b8496'
down_revision = 'e578255c657a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movies_actors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies_actors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.id'], name='movies_actors_actor_id_fkey'),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name='movies_actors_movie_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='movies_actors_pkey')
    )
    # ### end Alembic commands ###
