"""empty message

Revision ID: 748f37eca9d2
Revises: 93ddb048386a
Create Date: 2020-08-22 16:23:05.195337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748f37eca9d2'
down_revision = '93ddb048386a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('actorName', sa.String(length=80)))
    op.drop_column('actors', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column('actors', 'actorName')
    # ### end Alembic commands ###
