"""empty message

Revision ID: 86ac441ca630
Revises: 6d7a5ef90524
Create Date: 2020-08-29 13:17:40.609504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ac441ca630'
down_revision = '6d7a5ef90524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies_actors', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies_actors', 'test')
    # ### end Alembic commands ###
