"""empty message

Revision ID: 9499075aa894
Revises: 
Create Date: 2020-08-31 12:34:45.172469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9499075aa894'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('test', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'test')
    # ### end Alembic commands ###
