"""empty message

Revision ID: b792e039e464
Revises: f9423cf9f33f
Create Date: 2020-08-31 12:24:58.772332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b792e039e464'
down_revision = 'f9423cf9f33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('test', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
