"""empty message

Revision ID: be2edab8d150
Revises: 3e4cd16f30c1
Create Date: 2020-08-21 01:16:33.624262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be2edab8d150'
down_revision = '3e4cd16f30c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_details_test', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'movie_details_test')
    # ### end Alembic commands ###
