"""empty message

Revision ID: c0cda3642e87
Revises: 66027b4b8496
Create Date: 2020-08-27 10:21:52.254353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0cda3642e87'
down_revision = '66027b4b8496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('movies_actors_movie_id_fkey', 'movies_actors', type_='foreignkey')
    op.drop_constraint('movies_actors_actor_id_fkey', 'movies_actors', type_='foreignkey')
    op.create_foreign_key(None, 'movies_actors', 'movies', ['movie_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'movies_actors', 'actors', ['actor_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies_actors', type_='foreignkey')
    op.drop_constraint(None, 'movies_actors', type_='foreignkey')
    op.create_foreign_key('movies_actors_actor_id_fkey', 'movies_actors', 'actors', ['actor_id'], ['id'])
    op.create_foreign_key('movies_actors_movie_id_fkey', 'movies_actors', 'movies', ['movie_id'], ['id'])
    # ### end Alembic commands ###
