"""empty message

Revision ID: c9e56194283e
Revises: 9499075aa894
Create Date: 2020-08-31 12:35:12.896054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e56194283e'
down_revision = '9499075aa894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('test', sa.VARCHAR(length=6), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
