"""empty message

Revision ID: d08be1bae797
Revises: 358e447ffca1
Create Date: 2020-08-27 11:11:02.928079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd08be1bae797'
down_revision = '358e447ffca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies_actors', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.add_column('movies_actors', sa.Column('movie_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movies_actors', 'actors', ['actor_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'movies_actors', 'movies', ['movie_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies_actors', type_='foreignkey')
    op.drop_constraint(None, 'movies_actors', type_='foreignkey')
    op.drop_column('movies_actors', 'movie_id')
    op.drop_column('movies_actors', 'actor_id')
    # ### end Alembic commands ###
