"""empty message

Revision ID: f495af5797d5
Revises: b9cd90460db9
Create Date: 2020-08-31 16:43:46.465855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f495af5797d5'
down_revision = 'b9cd90460db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'release_date')
    op.drop_column('movies', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('test', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('movies', sa.Column('release_date', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
